-- 코드를 입력하세요
SELECT A.ORDER_ID
     , A.PRODUCT_ID
     , TO_CHAR(A.OUT_DATE, 'YYYY-MM-DD') AS OUT_DATE
     , CASE WHEN A.OUT_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-05-01', 'YYYY-MM-DD') 
            THEN '출고완료'
            WHEN A.OUT_DATE BETWEEN TO_DATE('2022-05-02', 'YYYY-MM-DD') AND TO_DATE('2022-12-31', 'YYYY-MM-DD')
            THEN '출고대기'
       ELSE '출고미정'
       END AS OUT_DATE
  FROM FOOD_ORDER A
 ORDER BY ORDER_ID ASC