-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME FROM (
    SELECT I.ANIMAL_ID, I.NAME, 
    TO_DATE(O.DATETIME) - TO_DATE(I.DATETIME) AS DATETIME
    FROM ANIMAL_INS I 
    RIGHT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DATETIME DESC)
WHERE ANIMAL_ID IS NOT NULL AND ROWNUM <= 2

