-- 코드를 입력하세요
SELECT 
EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
ROUND (COUNT (DISTINCT O.USER_ID) * 1.0 / (
    SELECT COUNT(*)
    FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O 
JOIN USER_INFO U 
ON O.USER_ID = U.USER_ID
WHERE EXTRACT(YEAR FROM U.JOINED) = 2021 
GROUP BY 
EXTRACT(YEAR FROM O.SALES_DATE),
EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY EXTRACT(YEAR FROM O.SALES_DATE),
EXTRACT(MONTH FROM O.SALES_DATE)


    