SELECT FLAVOR
FROM (
  SELECT F.FLAVOR, (F.TOTAL_ORDER + J.SUM_JULY_ORDERS) AS TOTAL_ORDERS
  FROM FIRST_HALF F
  JOIN (
      SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_JULY_ORDERS
      FROM JULY
      GROUP BY FLAVOR
  ) J ON F.FLAVOR = J.FLAVOR
  ORDER BY TOTAL_ORDERS DESC
)
WHERE ROWNUM <= 3;

