SELECT flavor
From (SELECT F.flavor,
    SUM(F.TOTAL_ORDER) + SUM (J.TOTAL_ORDER)  total
FROM FIRST_HALF F , JULY J
WHERE F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY total DESC) flavor
WHERE ROWNUM <= 3

