-- 코드를 작성해주세요

-- 실행 순서 GROUP BY > SELECT > WHERE > JOIN > SELECT > ORDER BY
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO  JOIN FISH_NAME_INFO  USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (
SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO 
GROUP BY FISH_TYPE
)
ORDER BY ID ASC;