-- 코드를 입력하세요
SELECT O.CATEGORY,S.MAX_PRICE, O.PRODUCT_NAME FROM FOOD_PRODUCT O
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT 
    GROUP BY CATEGORY 
    HAVING CATEGORY IN ('과자', '국', '식용유','김치')) S 
ON O.CATEGORY = S.CATEGORY AND O.PRICE = S.MAX_PRICE
ORDER BY MAX_PRICE DESC