-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, TO_CHAR(B.PUBLISHED_DATE,'YYYY-MM-DD') PUBLISHED_DATE
FROM (
    SELECT * FROM BOOK B
    WHERE B.CATEGORY IN('경제') ) B, AUTHOR A 
WHERE B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE